eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:https://sub-project-09.herokuapp.com/eureka}
  instance:
    hostname: sub-project-09.herokuapp.com
